version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: always
    ports:
      - "3000:80"
    env_file: ./packages/client/.env
  
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    env_file: ./packages/server/.env

  db:
    image: postgres:15.0
    restart: always
    volumes:
      - ${DB_MOUNT_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=big_yikes
