version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    restart: always
    ports:
      - "3000:80"
  
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    env_file: ./packages/server/.env

  db:
    image: mongo:4.2
    restart: always
    volumes:
      - ${DB_MOUNT_PATH}:/data/db
