import { blockTypes } from '../test/data';
import { Block } from './block';

const pos = { x: 1, y: 1 };
const b1 = new Block(blockTypes['1x1'], pos);

describe('block', () => {
  it('should have an autogenerated id', () => {
    expect(b1.id).toBeDefined();
  });

  it('should have a type property that exists in BlockTypes', () => {
    expect(b1.type).toEqual(blockTypes['1x1']);
  });

  it('should have a position that it is anchored at', () => {
    expect(b1.position).toEqual(pos);
  });

  it('should calculate its coordinates based on its position and type', () => {
    const block = new Block(blockTypes['1x2'], pos);
    expect(block.coordinates).toEqual([
      { x: 1, y: 1 },
      { x: 1, y: 2 },
    ]);
  });
});
