version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/workspace:cached
      # - $HOME/.aws/credentials:/home/me/.aws/credentials:ro
      # - $HOME/.aws/config:/home/me/.aws/config:ro
    command: sleep infinity
    network_mode: host
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /var/lib/dynamodb/data/ -cors http://localhost:8080
    restart: unless-stopped
    user: root
    volumes:
      - data:/var/lib/dynamodb/data
    ports:
      - 8000:8000
  dynamodb-viewer:
    image: taydy/dynamodb-manager
    ports:
      - 8080:80
volumes:
  data: {}
